### ISSUE TITLE
It doesn't work with CraftCMS v3.4.5

### ISSUE THREAD

**Issue by mateostabio** [fortrabbit/yii-memcached#1]
I am getting an error:

`Macbook-Pro Amilia % composer require fortrabbit/yii-memcached
Using version ^1.1 for fortrabbit/yii-memcached
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
 Problem 1
  - craftcms/cms 3.4.5 requires ext-zip * -> the requested PHP extension zip is missing from your system.
  - craftcms/cms 3.4.5 requires ext-zip * -> the requested PHP extension zip is missing from your system.
  - craftcms/cms 3.4.5 requires ext-zip * -> the requested PHP extension zip is missing from your system.
  - Installation request for craftcms/cms 3.4.5 -> satisfiable by craftcms/cms[3.4.5].`

**Comment by mateostabio** [comment]
Sorry, found a work around. First I did this, 
https://stackoverflow.com/a/58300437

and then I still had the issue here so I used this command and it worked.
`composer require fortrabbit/yii-memcached --ignore-platform-reqs`

**Comment by ostark** [comment]
@mateostabio `ext-zip` is a requirement of craft, but not of this package
