### ISSUE TITLE
Trying to update to CraftCMS 4

### ISSUE THREAD

**Issue by mateostabio** [fortrabbit/yii-memcached#9]
Hello, I tried updating the Craft 4 but noticed I am getting a lot of issues due to the plugin not being compatible with Craft 4.

**Comment by michaelfromtheoutfit** [comment]
Hey team - also looking to upgrade a bunch of projects that rely on this as well as craft-auto-migrate. Do you have plans to upgrade these to Craft 4? Thanks so much!

**Comment by ostark** [comment]
It's Craft 4 compatible 
https://github.com/fortrabbit/yii-memcached/releases/tag/1.4.0
